In [23]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [24]:
df=pd.read_csv("data.csv")
print(df.head())
print(df.shape)
print(df.dtypes)

   UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0    1     M14860    M                298.1                    308.6
1    2     L47181    L                298.2                    308.7
2    3     L47182    L                298.1                    308.5
3    4     L47183    L                298.2                    308.6
4    5     L47184    L                298.2                    308.7

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  TWF  \
0                    1551         42.8                0                0    0
1                    1408         46.3                3                0    0
2                    1498         49.4                5                0    0
3                    1433         39.5                7                0    0
4                    1408         40.0                9                0    0

   HDF  PWF  OSF  RNF
0    0    0    0    0
1    0    0    0    0
2    0    0    0    0
3    0    0    0    0
4    0    0    0    0
(10000, 14)
UDI                          int64
Product ID                     str
Type                           str
Air temperature [K]        float64
Process temperature [K]    float64
Rotational speed [rpm]       int64
Torque [Nm]                float64
Tool wear [min]              int64
Machine failure              int64
TWF                          int64
HDF                          int64
PWF                          int64
OSF                          int64
RNF                          int64
dtype: object

In [25]:
#checking if any of the columns have null values
print(df.isnull().sum())
print(df)

UDI                        0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
dtype: int64
        UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0         1     M14860    M                298.1                    308.6
1         2     L47181    L                298.2                    308.7
2         3     L47182    L                298.1                    308.5
3         4     L47183    L                298.2                    308.6
4         5     L47184    L                298.2                    308.7
...     ...        ...  ...                  ...                      ...
9995   9996     M24855    M                298.8                    308.4
9996   9997     H39410    H                298.9                    308.4
9997   9998     M24857    M                299.0                    308.6
9998   9999     H39412    H                299.0                    308.7
9999  10000     M24859    M                299.0                    308.7

      Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  \
0                       1551         42.8                0                0
1                       1408         46.3                3                0
2                       1498         49.4                5                0
3                       1433         39.5                7                0
4                       1408         40.0                9                0
...                      ...          ...              ...              ...
9995                    1604         29.5               14                0
9996                    1632         31.8               17                0
9997                    1645         33.4               22                0
9998                    1408         48.5               25                0
9999                    1500         40.2               30                0

      TWF  HDF  PWF  OSF  RNF
0       0    0    0    0    0
1       0    0    0    0    0
2       0    0    0    0    0
3       0    0    0    0    0
4       0    0    0    0    0
...   ...  ...  ...  ...  ...
9995    0    0    0    0    0
9996    0    0    0    0    0
9997    0    0    0    0    0
9998    0    0    0    0    0
9999    0    0    0    0    0

[10000 rows x 14 columns]

In [26]:
#checking by adding if there are na values
print(df.isna().sum())

UDI                        0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
dtype: int64

df=df.drop(columns=['UDI',                        0
'Product ID'])

In [27]:
#dropping un necessary columns
df=df.drop(columns=['UDI',                      
'Product ID'])
print(df.head())

  Type  Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0    M                298.1                    308.6                    1551
1    L                298.2                    308.7                    1408
2    L                298.1                    308.5                    1498
3    L                298.2                    308.6                    1433
4    L                298.2                    308.7                    1408

   Torque [Nm]  Tool wear [min]  Machine failure  TWF  HDF  PWF  OSF  RNF
0         42.8                0                0    0    0    0    0    0
1         46.3                3                0    0    0    0    0    0
2         49.4                5                0    0    0    0    0    0
3         39.5                7                0    0    0    0    0    0
4         40.0                9                0    0    0    0    0    0

In [28]:
print(df)

     Type  Air temperature [K]  Process temperature [K]  \
0       M                298.1                    308.6
1       L                298.2                    308.7
2       L                298.1                    308.5
3       L                298.2                    308.6
4       L                298.2                    308.7
...   ...                  ...                      ...
9995    M                298.8                    308.4
9996    H                298.9                    308.4
9997    M                299.0                    308.6
9998    H                299.0                    308.7
9999    M                299.0                    308.7

      Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  \
0                       1551         42.8                0                0
1                       1408         46.3                3                0
2                       1498         49.4                5                0
3                       1433         39.5                7                0
4                       1408         40.0                9                0
...                      ...          ...              ...              ...
9995                    1604         29.5               14                0
9996                    1632         31.8               17                0
9997                    1645         33.4               22                0
9998                    1408         48.5               25                0
9999                    1500         40.2               30                0

      TWF  HDF  PWF  OSF  RNF
0       0    0    0    0    0
1       0    0    0    0    0
2       0    0    0    0    0
3       0    0    0    0    0
4       0    0    0    0    0
...   ...  ...  ...  ...  ...
9995    0    0    0    0    0
9996    0    0    0    0    0
9997    0    0    0    0    0
9998    0    0    0    0    0
9999    0    0    0    0    0

[10000 rows x 12 columns]

In [29]:
#counting the number of failure machines
print(df.value_counts('Machine failure'))

Machine failure
0    9661
1     339
Name: count, dtype: int64

In [30]:
print(df.head())

  Type  Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0    M                298.1                    308.6                    1551
1    L                298.2                    308.7                    1408
2    L                298.1                    308.5                    1498
3    L                298.2                    308.6                    1433
4    L                298.2                    308.7                    1408

   Torque [Nm]  Tool wear [min]  Machine failure  TWF  HDF  PWF  OSF  RNF
0         42.8                0                0    0    0    0    0    0
1         46.3                3                0    0    0    0    0    0
2         49.4                5                0    0    0    0    0    0
3         39.5                7                0    0    0    0    0    0
4         40.0                9                0    0    0    0    0    0

In [31]:
#comparing machine failure and air temperature
pd.crosstab(df['Machine failure'],df['Air temperature [K]'])

Air temperature [K],295.3,295.4,295.5,295.6,295.7,295.8,295.9,296.0,296.1,296.2,...,303.6,303.7,303.8,303.9,304.0,304.1,304.2,304.3,304.4,304.5
Machine failure,,,,,,,,,,,,,,,,,,,,,
0,3,3,18,37,17,18,10,6,12,26,...,73,92,72,57,43,46,40,15,6,1
1,0,0,0,1,1,1,0,0,0,0,...,5,4,3,1,2,0,0,0,1,0

In [32]:
#calculating temperature difference
df['temperature difference']=df['Process temperature [K]']-df['Air temperature [K]']
print(df['temperature difference'])

0       10.5
1       10.5
2       10.4
3       10.4
4       10.5
        ...
9995     9.6
9996     9.5
9997     9.6
9998     9.7
9999     9.7
Name: temperature difference, Length: 10000, dtype: float64

In [33]:
#comparing machine failure and temperature difference
pd.crosstab(df['Machine failure'],df['temperature difference'])

temperature difference,7.6,7.6,7.7,7.7,7.8,7.8,7.9,7.9,8.0,8.1,...,11.6,11.7,11.7,11.8,11.8,11.9,11.9,12.0,12.1,12.1
Machine failure,,,,,,,,,,,,,,,,,,,,,
0,5,1,17,17,11,62,36,15,48,23,...,55,34,18,9,36,35,15,28,2,2
1,2,0,4,2,2,11,4,5,7,3,...,0,0,0,0,0,0,1,1,0,0

In [34]:
#checking if toolwear group effects the machine failure
df['tool_wear_group'] = pd.cut(df['Tool wear [min]'], 
                                bins=3, 
                                labels=['Low', 'Medium', 'High'])
print(pd.crosstab(df['tool_wear_group'], df['Machine failure'],
                  normalize='index') * 100)

Machine failure          0         1
tool_wear_group
Low              97.843187  2.156813
Medium           97.701750  2.298250
High             92.556054  7.443946

In [35]:
#checking if torque group effects the machine failure
['torque_group']=pd.cut(df['Torque [Nm]'],bins=3,labels=['Low','Medium','High'])
print(pd.crosstab(df['torque_group'],df['Machine failure'],normalize='index')*100)

SyntaxError: cannot assign to literal (104402360.py, line 2)

In [ ]:
df.head()

In [ ]:
#calcualting power and high_wear_risk for feature engineering
df['power']=df['Torque [Nm]']*df['Rotational speed [rpm]']
df['high_wear_risk']=(df['Tool wear [min]']<200).astype(int)
print(df['power'])
print(df['high_wear_risk'])

In [ ]:
df.head()

In [ ]:
#comparing power and high wear risk to machine failure
df[['power','high_wear_risk','Machine failure']]
print(pd.crosstab(df['high_wear_risk'],df['Machine failure']))

In [ ]:
df.to_csv('maintenance_cleaned.csv', index=False)
print("Saved! ✅")